### ISSUE TITLE
Docker container behind non-docker NGINX reverse proxy

### ISSUE THREAD

**Issue by jacksonp2008** [pierrecdn/phpipam#10]
NGINX not running as a container but on same machine as docker.

When I connect directly via http://site.com:8080/

it works fine.

When connecting through NGINX it fails, note it is https to the reverse proxy forwarding to http.

I have several other similar applications running as docker containers in this exact same configuration that work fine.  Any thoughts on what the issue might be?

docker-compose config:

```
version: '2'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxx
    restart: always
    volumes:
      - db_data:/var/lib/mysql
  ipam:
    depends_on:
      - mysql
    image: pierrecdn/phpipam
    environment:
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=xxxxx
    ports:
      - "8080:80"
volumes:
  db_data:
```

NGINX Config snippet

```
server {
	listen	443 ssl;
	server_name	kb1.xxxx.com;
	ssl_certificate /etc/ssl/certs/wxxxx.crt;
	ssl_certificate_key /etc/ssl/certs/wxxx.key;
	location / {
	proxy_pass http://127.0.0.1:8080/;
	proxy_set_header X-Real-IP $remote_addr;
	add_header X-Frame-Option ALLOWALL;
  	proxy_set_header Host $host;
  	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

```
Thank-you!
