### ISSUE TITLE
Cannot auto discover on Docker

### ISSUE THREAD

**Issue by huntson** [pierrecdn/phpipam#77]
I see that all recommendations for auto discovery rely on cron.  How does this get implemented in Docker?

**Comment by pierrecdn** [comment]
Hi,

> How does this get implemented in Docker?

I guess it's not. Welcome to uncharted territory :smile:. I unfortunately don't have that much time to perform the analysis.

**Comment by leleobhz** [comment]
@huntson Hello!

You can use [Ofelia](https://github.com/mcuadros/ofelia):

```yaml
version: '3.7'

services:
  ofelia:
    image: docker.io/mcuadros/ofelia:latest
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  phpipam:
    image: docker.io/pierrecdn/phpipam:latest
    labels:
      ofelia.enabled: true
      ofelia.job-exec.mysql-pingCheck-phpipam.schedule: "@every 5m"
      ofelia.job-exec.mysql-pingCheck-phpipam.command: "php /var/www/html/functions/scripts/pingCheck.php"
      ofelia.job-exec.mysql-discoveryCheck-phpipam.schedule: "@every 5m"
      ofelia.job-exec.mysql-discoveryCheck-phpipam.command: "php /var/www/html/functions/scripts/discoveryCheck.php"
    environment:
      - MYSQL_ENV_MYSQL_USER=phpipam
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=somepass
      - MYSQL_ENV_MYSQL_HOST=mariadb
    restart: unless-stopped
    depends_on:
      - mariadb
    logging:
      driver: journald

  mariadb:
    image: docker.io/library/mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=somepass
    volumes:
      - ./database:/var/lib/mysql
```

This compose is an example and need to be changed to fit you suits.
